/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Acceso;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author mavel
 */
public class CrearCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearCuenta.class.getName());

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
        
        txtNombre.putClientProperty("JTextField.placeholderText", "Nombre");
        txtNombre.putClientProperty("FlatLaf.style", "arc: 18; borderColor: #4A8C2D; focusedBorderColor: #4A8C2D; background: #F8F9F4");
        
        txtApellido.putClientProperty("JTextField.placeholderText", "Apellido");
        txtApellido.putClientProperty("FlatLaf.style", "arc: 18; borderColor: #4A8C2D; focusedBorderColor: #4A8C2D; background: #F8F9F4");
        
        txtCorreo.putClientProperty("JTextField.placeholderText", "Correo electrónico o Teléfono");
        txtCorreo.putClientProperty("FlatLaf.style", "arc: 18; borderColor: #4A8C2D; focusedBorderColor: #4A8C2D; background: #F8F9F4");
        
        txtPassword.putClientProperty("JTextField.placeholderText", "Contraseña");
        txtPassword.putClientProperty("FlatLaf.style", "arc: 18; borderColor: #4A8C2D; focusedBorderColor: #4A8C2D; background: #F8F9F4");
        
        txtPassword2.putClientProperty("JTextField.placeholderText", "Repetir Contraseña");
        txtPassword2.putClientProperty("FlatLaf.style", "arc: 18; borderColor: #4A8C2D; focusedBorderColor: #4A8C2D; background: #F8F9F4");

        setSize(320, 620);
        setResizable(false);
        setLocationRelativeTo(null);
         
        
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelcrearcuenta = new javax.swing.JLabel();
        jLabelmensajemotivador = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtPassword2 = new javax.swing.JPasswordField();
        txtNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jChecBoxTerminos = new javax.swing.JCheckBox();
        jLabelIniciarsesion = new javax.swing.JLabel();
        jLabelYatinescuenta1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Cuenta");
        setBackground(new java.awt.Color(229, 214, 193));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelcrearcuenta.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcrearcuenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelcrearcuenta.setForeground(new java.awt.Color(87, 145, 45));
        jLabelcrearcuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcrearcuenta.setText("Crear cuenta");
        getContentPane().add(jLabelcrearcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, -1));

        jLabelmensajemotivador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelmensajemotivador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmensajemotivador.setText("Únete a EcoLazo y se parte del cambio");
        getContentPane().add(jLabelmensajemotivador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 320, -1));

        txtApellido.setBackground(new java.awt.Color(234, 240, 226));
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMouseClicked(evt);
            }
        });
        txtApellido.addActionListener(this::txtApellidoActionPerformed);
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 230, 30));

        txtCorreo.setBackground(new java.awt.Color(234, 240, 226));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        txtCorreo.addActionListener(this::txtCorreoActionPerformed);
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, 30));

        txtPassword.setBackground(new java.awt.Color(234, 240, 226));
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 230, 30));

        txtPassword2.setBackground(new java.awt.Color(234, 240, 226));
        txtPassword2.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassword2MouseClicked(evt);
            }
        });
        txtPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassword2KeyTyped(evt);
            }
        });
        getContentPane().add(txtPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 230, 30));

        txtNombre.setBackground(new java.awt.Color(234, 240, 226));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(this::txtNombreActionPerformed);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 230, 30));

        jButton1.setBackground(new java.awt.Color(87, 145, 45));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear Cuenta");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 160, 30));

        jChecBoxTerminos.setText("Aceptar los Términos y Condiciones ");
        jChecBoxTerminos.addActionListener(this::jChecBoxTerminosActionPerformed);
        getContentPane().add(jChecBoxTerminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabelIniciarsesion.setForeground(new java.awt.Color(116, 186, 59));
        jLabelIniciarsesion.setText("Iniciar sesión");
        jLabelIniciarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIniciarsesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIniciarsesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIniciarsesionMouseExited(evt);
            }
        });
        getContentPane().add(jLabelIniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        jLabelYatinescuenta1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelYatinescuenta1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelYatinescuenta1.setText("Ya tienes cuenta? ");
        getContentPane().add(jLabelYatinescuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMouseClicked

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked

    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtPassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword2MouseClicked

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String correo = txtCorreo.getText().trim();
        String password = new String(txtPassword.getPassword());
        
        if (nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El campo 'Nombre' no puede estar vacío.", 
            "Atención", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        
        txtNombre.requestFocus(); // Coloca el cursor en el campo del error
        return; // Detiene la ejecución para que no avance al login
    }
        
    if(apellido.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El campo 'Apellido' no puede estar vacío.", 
            "Atención", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        txtApellido.requestFocus();
        return;
    }
    
    if(correo.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El campo 'Correo' no puede estar vacío.", 
            "Atención", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        txtCorreo.requestFocus();
        return;
    }
        
        if (password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Te falta ingresar la contraseña", 
            "Atención", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        
        txtPassword.requestFocus(); // Coloca el cursor en el password
        return; // Detiene la ejecución
    }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jChecBoxTerminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChecBoxTerminosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChecBoxTerminosActionPerformed

    private void jLabelIniciarsesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIniciarsesionMouseEntered
        jLabelIniciarsesion.setText("<html><u>Iniciar sesión</u></html>");
    }//GEN-LAST:event_jLabelIniciarsesionMouseEntered

    private void jLabelIniciarsesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIniciarsesionMouseExited
        jLabelIniciarsesion.setText("Iniciar sesión");
    }//GEN-LAST:event_jLabelIniciarsesionMouseExited

    private void jLabelIniciarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIniciarsesionMouseClicked
        Login ventana3 = new Login();
        ventana3.setLocationRelativeTo(null);
        ventana3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelIniciarsesionMouseClicked

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c)){
           evt.consume(); 
           return;
        }
        
        if (Character.isWhitespace(c)) {
        String textoActual = txtNombre.getText();
        
        // Bloquea si el campo está vacío (espacio al principio) OR si ya contiene un espacio
        if (textoActual.isEmpty() || textoActual.contains(" ")) {
            evt.consume(); 
            return;
        }
    }
        
        if (txtNombre.getText().length() >=12){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
       char c = evt.getKeyChar();
        
        if(Character.isDigit(c) || Character.isWhitespace(c)){
           evt.consume(); 
           return;
        }
        
        if (txtApellido.getText().length() >=9){ 
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isWhitespace(c)){
           evt.consume(); 
           return;
        }
       
        if (txtCorreo.getText().length() >=26){
            evt.consume();
        }
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
    
    String password = new String(txtPassword.getPassword());
        
    if(password.length()>=8){
        evt.consume();
    }
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtPassword2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassword2KeyTyped
    String password = new String(txtPassword2.getPassword());
        
    if(password.length()>=8){
        evt.consume();
    }
    }//GEN-LAST:event_txtPassword2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        com.formdev.flatlaf.FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearCuenta().setVisible(true));
    }
    
    
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jChecBoxTerminos;
    private javax.swing.JLabel jLabelIniciarsesion;
    private javax.swing.JLabel jLabelYatinescuenta1;
    private javax.swing.JLabel jLabelcrearcuenta;
    private javax.swing.JLabel jLabelmensajemotivador;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword2;
    // End of variables declaration//GEN-END:variables
}
