/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Acceso;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.UIManager;

/**
 *
 * @author mavel
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        getContentPane().setBackground(new java.awt.Color(248, 249, 244));
        jLabelLogo.setText("");
        jLabelLogo.setOpaque(false);
        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new FlatSVGIcon("Recursos/ImagenesSVG/Logo.svg", 160, 108));
        
        jLabel1.setIcon(new FlatSVGIcon("Recursos/ImagenesSVG/Hojas2.svg", 60, 80));
        jLabel2.setIcon(new FlatSVGIcon("Recursos/ImagenesSVG/Hojas4.svg", 30, 90));
        jLabel3.setIcon(new FlatSVGIcon("Recursos/ImagenesSVG/Ondas.svg", 320, 110));
        jLabel4.setIcon(new FlatSVGIcon("Recursos/ImagenesSVG/Hojas3.svg", 70, 100));
        jLabel7.setIcon(new FlatSVGIcon("Recursos/ImagenesSVG/Usuario.svg", 12, 15));
        jLabel6.setIcon(new FlatSVGIcon("Recursos/ImagenesSVG/Candado.svg", 12, 15));
        
        
        
        txtCorreo.putClientProperty("JTextField.placeholderText", "Correo electronico o Telefono");
        txtCorreo.putClientProperty("FlatLaf.style", "arc: 18; borderColor: #4A8C2D; focusedBorderColor: #4A8C2D; background: #F8F9F4");

        txtPassword.putClientProperty("JTextField.placeholderText", "Contraseña");
        txtPassword.putClientProperty("FlatLaf.style", "arc: 18; borderColor: #4A8C2D; focusedBorderColor: #4A8C2D; background: #F8F9F4");

        setSize(320, 620);
        setResizable(false);
        setLocationRelativeTo(null);

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        EcoLazo1 = new javax.swing.JLabel();
        EcoLazo = new javax.swing.JLabel();
        jLabelslogan = new javax.swing.JLabel();
        jLabelbienvenido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabelolvidastetucontrasena = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelnotienescuenta = new javax.swing.JLabel();
        jLabelregistraser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(229, 214, 193));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 60, 80));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 30, 90));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 80, 110));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 320, 160));

        jLabelLogo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jPanel1.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 320, 220));

        EcoLazo1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        EcoLazo1.setForeground(new java.awt.Color(101, 175, 43));
        EcoLazo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EcoLazo1.setText("Eco");
        jPanel1.add(EcoLazo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 150, 50));

        EcoLazo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        EcoLazo.setForeground(new java.awt.Color(37, 152, 73));
        EcoLazo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EcoLazo.setText("Lazo");
        jPanel1.add(EcoLazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 170, 50));

        jLabelslogan.setBackground(new java.awt.Color(255, 255, 255));
        jLabelslogan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelslogan.setForeground(new java.awt.Color(0, 0, 0));
        jLabelslogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelslogan.setText("Dona, Comparte, Reutiliza");
        jPanel1.add(jLabelslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 320, -1));

        jLabelbienvenido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelbienvenido.setForeground(new java.awt.Color(0, 0, 0));
        jLabelbienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelbienvenido.setText("Bienvenido");
        jPanel1.add(jLabelbienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 320, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 325, 12, 20));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 12, 30));

        txtCorreo.setBackground(new java.awt.Color(234, 240, 226));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        txtCorreo.addActionListener(this::txtCorreoActionPerformed);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 220, 30));

        txtPassword.setBackground(new java.awt.Color(234, 240, 226));
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 220, 30));

        jLabelolvidastetucontrasena.setBackground(new java.awt.Color(255, 255, 255));
        jLabelolvidastetucontrasena.setForeground(new java.awt.Color(87, 145, 45));
        jLabelolvidastetucontrasena.setText("¿Olvidaste tu contraseña?");
        jLabelolvidastetucontrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelolvidastetucontrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelolvidastetucontrasenaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelolvidastetucontrasenaMouseExited(evt);
            }
        });
        jPanel1.add(jLabelolvidastetucontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 140, 20));

        jButton1.setBackground(new java.awt.Color(87, 145, 45));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar sesión");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 160, 30));

        jLabelnotienescuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelnotienescuenta.setForeground(new java.awt.Color(0, 0, 0));
        jLabelnotienescuenta.setText("¿No tienes cuenta? ");
        jPanel1.add(jLabelnotienescuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabelregistraser.setBackground(new java.awt.Color(255, 255, 255));
        jLabelregistraser.setForeground(new java.awt.Color(87, 145, 45));
        jLabelregistraser.setText("Registrarse");
        jLabelregistraser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelregistraser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelregistraserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelregistraserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelregistraserMouseExited(evt);
            }
        });
        jPanel1.add(jLabelregistraser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 80, -1));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
       
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void jLabelolvidastetucontrasenaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelolvidastetucontrasenaMouseEntered
        jLabelolvidastetucontrasena.setText("<html><u>\u00bfOlvidaste tu contrase\u00f1a?</u></html>");
    }//GEN-LAST:event_jLabelolvidastetucontrasenaMouseEntered

    private void jLabelolvidastetucontrasenaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelolvidastetucontrasenaMouseExited
      jLabelolvidastetucontrasena.setText("\u00bfOlvidaste tu contrase\u00f1a?");
    }//GEN-LAST:event_jLabelolvidastetucontrasenaMouseExited

    private void jLabelregistraserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelregistraserMouseEntered
        jLabelregistraser.setText("<html><u>Registrarse</u></html>");
    }//GEN-LAST:event_jLabelregistraserMouseEntered

    private void jLabelregistraserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelregistraserMouseExited
        jLabelregistraser.setText("Registrarse");
    }//GEN-LAST:event_jLabelregistraserMouseExited

    private void jLabelregistraserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelregistraserMouseClicked
        CrearCuenta ventana2 = new CrearCuenta();
        ventana2.setLocationRelativeTo(null);
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelregistraserMouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed
    
    
      

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        com.formdev.flatlaf.FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EcoLazo;
    private javax.swing.JLabel EcoLazo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelbienvenido;
    private javax.swing.JLabel jLabelnotienescuenta;
    private javax.swing.JLabel jLabelolvidastetucontrasena;
    private javax.swing.JLabel jLabelregistraser;
    private javax.swing.JLabel jLabelslogan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
