/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Acceso;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.UIManager;

/**
 *
 * @author mavel
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
     
        getContentPane().setBackground(new java.awt.Color(248, 249, 244));
        jLabelLogo.setText("");
        jLabelLogo.setOpaque(false);
        jLabelLogo.setIcon(new FlatSVGIcon("Imagenes/Logo.svg", 200, 135));
        txtCorreo.putClientProperty("JTextField.placeholderText", "Correo electrónico o Teléfono");
        txtCorreo.putClientProperty("FlatLaf.style", "arc: 18; borderColor: #4A8C2D; focusedBorderColor: #4A8C2D; background: #F8F9F4");

        txtPassword.putClientProperty("JTextField.placeholderText", "Contraseña");
        txtPassword.putClientProperty("JComponent.roundRect", true);
        txtPassword.putClientProperty("FlatLaf.style", "arc: 18; borderColor: #4A8C2D; focusedBorderColor: #4A8C2D; background: #F8F9F4");
        
        
        setSize(320, 620);
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        EcoLazo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabelhojas3 = new javax.swing.JLabel();
        jLabelhojas1 = new javax.swing.JLabel();
        jLabelhojas2 = new javax.swing.JLabel();
        jLabelcandado = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabelolvidastetucontrasena = new javax.swing.JLabel();
        jLabelnotienescuenta = new javax.swing.JLabel();
        jLabelregistraser = new javax.swing.JLabel();
        jLabelondas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(229, 214, 193));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 200, 180));

        EcoLazo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        EcoLazo.setForeground(new java.awt.Color(39, 153, 69));
        EcoLazo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EcoLazo.setText("EcoLazo");
        getContentPane().add(EcoLazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dona, Comparte, Reutiliza");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 320, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 250, 320, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        txtCorreo.setBackground(new java.awt.Color(234, 240, 226));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        txtCorreo.addActionListener(this::txtCorreoActionPerformed);
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 230, 30));

        jLabelhojas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hojas3.png"))); // NOI18N
        getContentPane().add(jLabelhojas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 80, 100));

        jLabelhojas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hojas2.png"))); // NOI18N
        getContentPane().add(jLabelhojas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 100));

        jLabelhojas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hojas4.png"))); // NOI18N
        getContentPane().add(jLabelhojas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 30, 80));

        jLabelcandado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/candado.png"))); // NOI18N
        getContentPane().add(jLabelcandado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 30));

        txtPassword.setBackground(new java.awt.Color(234, 240, 226));
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 230, 30));

        jButton1.setBackground(new java.awt.Color(87, 145, 45));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar sesión");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 160, 30));

        jLabelolvidastetucontrasena.setBackground(new java.awt.Color(255, 255, 255));
        jLabelolvidastetucontrasena.setForeground(new java.awt.Color(87, 145, 45));
        jLabelolvidastetucontrasena.setText("Olvidaste tu contraseña?");
        jLabelolvidastetucontrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelolvidastetucontrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelolvidastetucontrasenaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelolvidastetucontrasenaMouseExited(evt);
            }
        });
        getContentPane().add(jLabelolvidastetucontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 376, 140, 20));

        jLabelnotienescuenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelnotienescuenta.setForeground(new java.awt.Color(0, 0, 0));
        jLabelnotienescuenta.setText("No tienes cuenta? ");
        getContentPane().add(jLabelnotienescuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        jLabelregistraser.setBackground(new java.awt.Color(255, 255, 255));
        jLabelregistraser.setForeground(new java.awt.Color(87, 145, 45));
        jLabelregistraser.setText("Registrarse");
        jLabelregistraser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelregistraser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelregistraserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelregistraserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelregistraserMouseExited(evt);
            }
        });
        getContentPane().add(jLabelregistraser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 80, -1));

        jLabelondas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelondas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelondas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelondas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ondas.png"))); // NOI18N
        jLabelondas.setText("jLabel4");
        getContentPane().add(jLabelondas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 320, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
       
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void jLabelolvidastetucontrasenaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelolvidastetucontrasenaMouseEntered
        jLabelolvidastetucontrasena.setText("<html><u>Olvisaste tu contraseña?</u></html>");
    }//GEN-LAST:event_jLabelolvidastetucontrasenaMouseEntered

    private void jLabelolvidastetucontrasenaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelolvidastetucontrasenaMouseExited
      jLabelolvidastetucontrasena.setText("Olvisaste tu contraseña?");
    }//GEN-LAST:event_jLabelolvidastetucontrasenaMouseExited

    private void jLabelregistraserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelregistraserMouseEntered
        jLabelregistraser.setText("<html><u>Registrarse</u></html>");
    }//GEN-LAST:event_jLabelregistraserMouseEntered

    private void jLabelregistraserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelregistraserMouseExited
        jLabelregistraser.setText("Registrarse");
    }//GEN-LAST:event_jLabelregistraserMouseExited

    private void jLabelregistraserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelregistraserMouseClicked
        CrearCuenta ventana2 = new CrearCuenta();
        ventana2.setLocationRelativeTo(null);
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelregistraserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        com.formdev.flatlaf.FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EcoLazo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelcandado;
    private javax.swing.JLabel jLabelhojas1;
    private javax.swing.JLabel jLabelhojas2;
    private javax.swing.JLabel jLabelhojas3;
    private javax.swing.JLabel jLabelnotienescuenta;
    private javax.swing.JLabel jLabelolvidastetucontrasena;
    private javax.swing.JLabel jLabelondas;
    private javax.swing.JLabel jLabelregistraser;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
