/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_2;

/**
 *
 * @author hinol
 */
public class Mis_Publicaciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mis_Publicaciones.class.getName());

    /**
     * Creates new form Mis_Publicaciones
     */
    public Mis_Publicaciones() {
        initComponents();
        setSize(320, 620);
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbnactivo = new javax.swing.JButton();
        jbnborradores = new javax.swing.JButton();
        jbnhistorial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbnpublicar = new javax.swing.JButton();
        jbnborrar = new javax.swing.JButton();
        jbneditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbneditar2 = new javax.swing.JButton();
        jbnborrar2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jbneditar3 = new javax.swing.JButton();
        jbnborrar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbnactivo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbnactivo.setText("Activos (3)");
        getContentPane().add(jbnactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        jbnborradores.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbnborradores.setText("Borradores (1)");
        getContentPane().add(jbnborradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, -1));

        jbnhistorial.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbnhistorial.setText("Historial (2)");
        getContentPane().add(jbnhistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_png/sillas.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, 70));

        jLabel3.setText("Silla de madera");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 100, -1));

        jLabel4.setText("Muebles");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel5.setText("2 interesados");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jbnpublicar.setForeground(new java.awt.Color(51, 153, 0));
        jbnpublicar.setText("Publicar nuevo objeto");
        jbnpublicar.addActionListener(this::jbnpublicarActionPerformed);
        getContentPane().add(jbnpublicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 503, 240, 30));

        jbnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_png/botebasura.png"))); // NOI18N
        getContentPane().add(jbnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 20, -1));

        jbneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_png/lapiz.png"))); // NOI18N
        getContentPane().add(jbneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 20, -1));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_png/sudadera.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, 70));

        jLabel8.setText("Sudadera negra");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel9.setText("Ropa");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel10.setText("1 interesado");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jbneditar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_png/lapiz.png"))); // NOI18N
        jbneditar2.addActionListener(this::jbneditar2ActionPerformed);
        getContentPane().add(jbneditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 20, -1));

        jbnborrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_png/botebasura.png"))); // NOI18N
        getContentPane().add(jbnborrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 20, -1));

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 0)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, 90));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_png/libro.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, 70));

        jLabel13.setText("The metamorphosis");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel14.setText("Libro");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel15.setText("3 interesados");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, 20));

        jbneditar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_png/lapiz.png"))); // NOI18N
        getContentPane().add(jbneditar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 20, -1));

        jbnborrar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_png/botebasura.png"))); // NOI18N
        getContentPane().add(jbnborrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbneditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbneditar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbneditar2ActionPerformed

    private void jbnpublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnpublicarActionPerformed
        Publicar_Objeto ventanaPubObj = new Publicar_Objeto();
        ventanaPubObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnpublicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mis_Publicaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbnactivo;
    private javax.swing.JButton jbnborradores;
    private javax.swing.JButton jbnborrar;
    private javax.swing.JButton jbnborrar2;
    private javax.swing.JButton jbnborrar3;
    private javax.swing.JButton jbneditar;
    private javax.swing.JButton jbneditar2;
    private javax.swing.JButton jbneditar3;
    private javax.swing.JButton jbnhistorial;
    private javax.swing.JButton jbnpublicar;
    // End of variables declaration//GEN-END:variables
}
